// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASogpkz4yBnj97_Xr5LKAPezeSgwO7n94',
    appId: '1:891139730732:web:aeeb3f64c3b9c620bad089',
    messagingSenderId: '891139730732',
    projectId: 'patrulha-conectada',
    authDomain: 'patrulha-conectada.firebaseapp.com',
    storageBucket: 'patrulha-conectada.firebasestorage.app',
    measurementId: 'G-36X36MPPK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbOfHDF3VXFYGc0HL7KmFTNTTlLzlu-js',
    appId: '1:891139730732:android:c8eb59bf2dd45980bad089',
    messagingSenderId: '891139730732',
    projectId: 'patrulha-conectada',
    storageBucket: 'patrulha-conectada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWJl_gXPGeDvsu6qDu89ISQMU8Cghz5d8',
    appId: '1:891139730732:ios:d4a57d7f3c429f83bad089',
    messagingSenderId: '891139730732',
    projectId: 'patrulha-conectada',
    storageBucket: 'patrulha-conectada.firebasestorage.app',
    iosBundleId: 'com.example.patrulhaConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWJl_gXPGeDvsu6qDu89ISQMU8Cghz5d8',
    appId: '1:891139730732:ios:d4a57d7f3c429f83bad089',
    messagingSenderId: '891139730732',
    projectId: 'patrulha-conectada',
    storageBucket: 'patrulha-conectada.firebasestorage.app',
    iosBundleId: 'com.example.patrulhaConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASogpkz4yBnj97_Xr5LKAPezeSgwO7n94',
    appId: '1:891139730732:web:56fa960896403cb0bad089',
    messagingSenderId: '891139730732',
    projectId: 'patrulha-conectada',
    authDomain: 'patrulha-conectada.firebaseapp.com',
    storageBucket: 'patrulha-conectada.firebasestorage.app',
    measurementId: 'G-4W6LNHD9BW',
  );

}